name: Repoclean

on:
  schedule:
    - cron:  00 16 * * 3
  workflow_dispatch: # manually triggered

jobs:
  repoclean:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout munki code
      uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
      with:
        repository: munki/munki
        fetch-depth: 1
        ref: e2d88c009108b84613cfd88c4a0c5a008dc5df76
        path: munki

    - name: Checkout your munki LFS repo
      uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
      with:
        fetch-depth: 1
        repository: 26fiftysix/autopkg-repo
        ref: refs/heads/master
        path: munki_repo
        token: ${{ secrets.AUTOPKG_GITHUB_TOKEN }}

    - name: Run Munki repoclean
      run: |
        yes | python3 munki/code/client/repoclean --keep 2 munki_repo

    - name: Configure Git
      run: |
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Check for changes
      run: |
        cd munki_repo/
        git checkout -b "repoclean-`date +'%Y-%m-%d'`"
        if git diff --exit-code; then
          echo "changes_exists=false" >> $GITHUB_ENV
        else
          echo "changes_exists=true" >> $GITHUB_ENV
        fi

    - name: Commit and Push
      if: ${{ env.changes_exists == 'true' }}
      run: |
        cd munki_repo/
        git add -u pkgsinfo/ pkgs/
        git commit -m "`date +'%Y-%m-%d'` repoclean"
        git push --set-upstream origin "repoclean-`date +'%Y-%m-%d'`"

    - name: Nothing to commit
      if: ${{ env.changes_exists == 'false' }}
      run: |
        echo "Nothing to commit."
